swagger: "2.0"
info:
  version: "1.0.0"
  title: "ArcMentors Web Framework"
basePath: "/api/v1"
tags:
  - name: "item"
schemes:
  - "https"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /item/{item_id}:
    get:
      tags:
        - "item"
      summary: "Get a item"
      operationId: "get_item"
      parameters:
        - name: "item_id"
          in: "path"
          description: "The id of the item to retrieve"
          required: true
          type: "string"
      responses:
        200:
          description: "Successfully retrived item"
          schema:
            $ref: "#/definitions/Item"
        404:
          description: "Item doesn't exist"
      x-swagger-router-controller: "test_api.web.controllers.items_controller"
    delete:
      tags:
        - "item"
      summary: "Remove a item"
      operationId: "remove_item"
      parameters:
        - name: "item_id"
          in: "path"
          description: "The id of the item to be removed"
          required: true
          type: "string"
      responses:
        202:
          description: "Successfully deleted item"
        404:
          description: "Item doesn't exist"
      x-swagger-router-controller: "test_api.web.controllers.items_controller"
    put:
      tags:
        - "item"
      summary: "Update and replace an item"
      operationId: "update_item"
      parameters:
        - name: "item_id"
          in: "path"
          description: "The id of the item to be update"
          required: true
          type: "string"
        - name: "Item"
          in: "body"
          required: true
          schema:
            $ref: "#/definitions/Item"
      responses:
        200:
          description: "Successfully updated item"
        404:
          description: "Item doesn't exist"
      x-swagger-router-controller: "test_api.web.controllers.items_controller"
  /item:
    get:
      tags:
        - "item"
      summary: "Gets all items"
      operationId: "get_all_items"
      responses:
        200:
          description: "Successfully received all items."
          schema:
            $ref: "#/definitions/Items"
      x-swagger-router-controller: "test_api.web.controllers.items_controller"
    post:
      tags:
        - "item"
      summary: "Add a new item"
      operationId: "add_item"
      parameters:
        - in: "body"
          name: "body"
          description: "Item to add"
          required: true
          schema:
            $ref: "#/definitions/Item"
      responses:
        201:
          description: "Item added"
      x-swagger-router-controller: "test_api.web.controllers.items_controller"
definitions:
  Items:
    type: array
    items:
      $ref: "#/definitions/Item"
  Item:
    type: "object"
    required:
      - "name"
      - "category"
      - "price"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      category:
        type: "string"
      price:
        type: "number"
        format: "float"
    example:
      id: 1
      name: "Touch & Scroll Wireless Mouse"
      category: "Computer Accessories"
      price: 23.49